title: Base
url: "https://www.kbwesrenshaw.com"
baseurl:

timezone: Etc/UTC

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"