# ----
# Site

title: Base
#url: "https://kb.wesrenshaw.com"
url: "https://c0smos.github.io"
baseurl:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: 
# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  sets:

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

